version: "3.9"

services:
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/examen
      - DATABASE_USERNAME=mysql
      - DATABASE_PASSWORD=mysql
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      POSTGRES_USER: mysql
      POSTGRES_PASSWORD: mysql
      POSTGRES_DB: mysql